-- Create schemas

-- Create tables
CREATE TABLE IF NOT EXISTS INSTRUCTOR
(
    ID INTEGER NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS ALUMNO
(
    ID INTEGER NOT NULL,
    GRUPO_ID INTEGER,
    PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS CURSO
(
    ID INTEGER NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS GRUPO
(
    ID INTEGER NOT NULL,
    CURSO_ID INTEGER,
    INSTRUCTOR_ID INTEGER,
    HORARIO_ID INTEGER,
    CURSO_NOMBRE VARCHAR(255),
    PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS HORARIO
(
    ID INTEGER NOT NULL,
    PRIMARY KEY(ID)
);


-- Create FKs
ALTER TABLE GRUPO
    ADD    FOREIGN KEY (INSTRUCTOR_ID)
    REFERENCES INSTRUCTOR(ID)
    MATCH SIMPLE
;
    
ALTER TABLE GRUPO
    ADD    FOREIGN KEY (HORARIO_ID)
    REFERENCES HORARIO(ID)
    MATCH SIMPLE
;
    
ALTER TABLE GRUPO
    ADD    FOREIGN KEY (CURSO_ID)
    REFERENCES CURSO(ID)
    MATCH SIMPLE
;
    
ALTER TABLE ALUMNO
    ADD    FOREIGN KEY (GRUPO_ID)
    REFERENCES GRUPO(ID)
    MATCH SIMPLE
;
    

